// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Ticket struct {
	ID          int64
	Status      string
	Title       string
	Description sql.NullString
	Rank        int64
}
