// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	AddTicket(ctx context.Context, arg AddTicketParams) (AddTicketRow, error)
	DeleteTicket(ctx context.Context, id int64) error
	GetTicketById(ctx context.Context, id int64) (Ticket, error)
	GetTickets(ctx context.Context) ([]Ticket, error)
	UpdateRank(ctx context.Context, arg UpdateRankParams) error
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
	UpdateTicketContent(ctx context.Context, arg UpdateTicketContentParams) error
}

var _ Querier = (*Queries)(nil)
