// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	AddTicket(ctx context.Context, arg AddTicketParams) (int64, error)
	GetTicketById(ctx context.Context, id int64) (Ticket, error)
	GetTickets(ctx context.Context) ([]Ticket, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
}

var _ Querier = (*Queries)(nil)
