// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const addTicket = `-- name: AddTicket :one
insert into tickets (
  title, description, rank
)
values (
  ?1, ?2, (select coalesce(max(rank) + 1000000, 0) from tickets)
)
returning id, rank
`

type AddTicketParams struct {
	Title       string
	Description sql.NullString
}

type AddTicketRow struct {
	ID   int64
	Rank int64
}

func (q *Queries) AddTicket(ctx context.Context, arg AddTicketParams) (AddTicketRow, error) {
	row := q.db.QueryRowContext(ctx, addTicket, arg.Title, arg.Description)
	var i AddTicketRow
	err := row.Scan(&i.ID, &i.Rank)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
delete from tickets
where id = ?1
`

func (q *Queries) DeleteTicket(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTicket, id)
	return err
}

const getTicketById = `-- name: GetTicketById :one
SELECT id, status, title, description, rank FROM tickets
WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetTicketById(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketById, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Rank,
	)
	return i, err
}

const getTickets = `-- name: GetTickets :many
SELECT id, status, title, description, rank FROM tickets
order by rank, id
`

func (q *Queries) GetTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRank = `-- name: UpdateRank :exec
update tickets
set rank = ?1
where id = ?2
`

type UpdateRankParams struct {
	Rank int64
	ID   int64
}

func (q *Queries) UpdateRank(ctx context.Context, arg UpdateRankParams) error {
	_, err := q.db.ExecContext(ctx, updateRank, arg.Rank, arg.ID)
	return err
}

const updateStatus = `-- name: UpdateStatus :exec
update tickets
set status = ?1
where id = ?2
`

type UpdateStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus, arg.Status, arg.ID)
	return err
}

const updateTicketContent = `-- name: UpdateTicketContent :exec
update tickets
set
  title = ?1,
  description = ?2
where id = ?3
`

type UpdateTicketContentParams struct {
	Title       string
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateTicketContent(ctx context.Context, arg UpdateTicketContentParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketContent, arg.Title, arg.Description, arg.ID)
	return err
}
