// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const addTicket = `-- name: AddTicket :one
insert into tickets (
  title, description
)
values (
  ?1, ?2
)
returning id
`

type AddTicketParams struct {
	Title       string
	Description sql.NullString
}

func (q *Queries) AddTicket(ctx context.Context, arg AddTicketParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addTicket, arg.Title, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTicketById = `-- name: GetTicketById :one
SELECT id, title, description, status FROM tickets
WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetTicketById(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketById, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const getTickets = `-- name: GetTickets :many
SELECT id, title, description, status FROM tickets
`

func (q *Queries) GetTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :exec
update tickets
set status = ?1
where id = ?2
`

type UpdateStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus, arg.Status, arg.ID)
	return err
}
