// Code generated by "stringerParser -type=Status"; DO NOT EDIT.

package ticket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringerParser command to generate them again.
	var x [1]struct{}
	_ = x[Todo-0]
	_ = x[InProgress-1]
	_ = x[Done-2]
}

const _Status_name = "TodoInProgressDone"

var _Status_index = [...]uint8{0, 4, 14, 18}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
func (i *Status) Parse(value string) Status {
	for l, j := uint8(len(value)), 1; j < len(_Status_index); j++ {
		if _Status_index[j]-_Status_index[j-1] == l && value == _Status_name[_Status_index[j-1]:_Status_index[j]] {
			*i = Status(j - 1)
			return *i
		}
	}
	// Return the zero-value by default
	*i = Status(0)
	return *i
}
